name: Hub
main: NamelessLeaf\Hub\Main
author: NamelessLeaf
version: "1.0"
description: "Plugin For NamelessNetwork"
api: 3.17.2
commands:
 Hub:
  description: "Go To Hub"
  permission: use.hubnameless
