name: hub
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11]
author: NamelessLeaf
version: 1.0
main: NamelessLeaf\hub\pvp

command:
	cmdname:
		description: Go Back To NamelessLand's Hub
	cmd2name:
		description: Go To NamelessLand's Hub

# Permissions 
permissions:
	cmdname.command:
		default: true
	cmd2name.command:
		default: true
